# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import keyValueStore_pb2 as keyValueStore__pb2


class KeyValueStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.put = channel.unary_unary(
                '/KeyValueStore/put',
                request_serializer=keyValueStore__pb2.PutRequest.SerializeToString,
                response_deserializer=keyValueStore__pb2.PutResponse.FromString,
                )
        self.get = channel.unary_unary(
                '/KeyValueStore/get',
                request_serializer=keyValueStore__pb2.GetRequest.SerializeToString,
                response_deserializer=keyValueStore__pb2.GetResponse.FromString,
                )
        self.getAllKeys = channel.unary_stream(
                '/KeyValueStore/getAllKeys',
                request_serializer=keyValueStore__pb2.GetAllKeysRequest.SerializeToString,
                response_deserializer=keyValueStore__pb2.GetKeyResponse.FromString,
                )


class KeyValueStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def put(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAllKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'put': grpc.unary_unary_rpc_method_handler(
                    servicer.put,
                    request_deserializer=keyValueStore__pb2.PutRequest.FromString,
                    response_serializer=keyValueStore__pb2.PutResponse.SerializeToString,
            ),
            'get': grpc.unary_unary_rpc_method_handler(
                    servicer.get,
                    request_deserializer=keyValueStore__pb2.GetRequest.FromString,
                    response_serializer=keyValueStore__pb2.GetResponse.SerializeToString,
            ),
            'getAllKeys': grpc.unary_stream_rpc_method_handler(
                    servicer.getAllKeys,
                    request_deserializer=keyValueStore__pb2.GetAllKeysRequest.FromString,
                    response_serializer=keyValueStore__pb2.GetKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KeyValueStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeyValueStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def put(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/put',
            keyValueStore__pb2.PutRequest.SerializeToString,
            keyValueStore__pb2.PutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/get',
            keyValueStore__pb2.GetRequest.SerializeToString,
            keyValueStore__pb2.GetResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAllKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/KeyValueStore/getAllKeys',
            keyValueStore__pb2.GetAllKeysRequest.SerializeToString,
            keyValueStore__pb2.GetKeyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
